# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            M
tagline:          'Every thought'
description:      'Every thought of me'
url:              http://jessiesmt.github.io
baseurl:          /

author:
  name:           'Jessie'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jessiesmt/jessiesmt.github.io
